name: Publish

on:
  push:
    tags:
      - "**"
    branches:
      - master

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    # if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm install
          pnpm postinstall
          pnpm build
          pnpm package

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "./release/build/*.@(exe|dmg|zip)"
