name: Publish

on:
  push:
    tags:
      - "**"
    branches:
      - master

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    # if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm install
          pnpm postinstall

      - name: Import Certificate
        run: |
          echo "${{ secrets.APPLE_CERT_BASE64 }}" | base64 --decode > certificate.p12
          security create-keychain -p actions build.keychain
          security default-keychain -s build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.CSC_KEY_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k actions build.keychain

      - name: Build
        run: |
          pnpm build
          CSC_FOR_PULL_REQUEST=true pnpm package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: release/build/*.dmg

      - name: Create Release Notes File
        id: var
        run: |
          node ./.github/scripts/createReleaseNotes.js

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "./release/build/*.@(exe|dmg|zip)"
